std_interfaces/msg/Header.msg

This has been proposed as far back as six years ago, but was avoided in ROS 1 to prevent disruption to existing code. The idea is that having a sequence number that is inconsistently set by the middleware, and often set by users, only to have the middleware override it, doesn't really make sense. Rather the middleware should give the sequence number to the subscriber through a separate channel (not as part of the message struct), and prevent the publishing user from setting it manually (it doesn't make sense for them to do so). Therefore it doesn't need to be a field in the `.msg`.
Also, unlike `stamp` and `frame_id`, `seq` is not needed to relate one piece of data to another. Both `stamp` and `frame_id` are values with global significance and are values that the middleware cannot …

remove seq number from Header.msg

---

geometry_msgs/CMakeLists.txt
sensor_msgs/CMakeLists.txt
std_msgs/CMakeLists.txt

As we discussed on the mailing list.
The only thing I could think we might do differently is that we could add an option to opt-in or opt-out of building these messages using an environment variable. On the one hand that's a strange (surprising) side effect, but on the other we could re-enable these messages for the nightly/packaging jobs more easily.

disable many uncommonly used messages temporarly to save build time

---

actionlib_msgs/CMakeLists.txt
builtin_interfaces/CMakeLists.txt
diagnostic_msgs/CMakeLists.txt
geometry_msgs/CMakeLists.txt
nav_msgs/CMakeLists.txt
sensor_msgs/CMakeLists.txt
shape_msgs/CMakeLists.txt
std_msgs/CMakeLists.txt
std_srvs/CMakeLists.txt
stereo_msgs/CMakeLists.txt
trajectory_msgs/CMakeLists.txt
visualization_msgs/CMakeLists.txt

Connect to ros2/rosidl#158 and requires that `rosidl_default_runtime` doesn't export all the typesupport packages anymore.

fix export of rosidl_default_runtime

---

diagnostic_msgs/CMakeLists.txt
diagnostic_msgs/srv/AddDiagnostics.srv
geometry_msgs/CMakeLists.txt
geometry_msgs/msg/Accel.msg
geometry_msgs/msg/AccelStamped.msg
geometry_msgs/msg/AccelWithCovariance.msg
geometry_msgs/msg/AccelWithCovarianceStamped.msg
geometry_msgs/msg/Inertia.msg
geometry_msgs/msg/InertiaStamped.msg
nav_msgs/CMakeLists.txt
nav_msgs/srv/SetMap.srv
sensor_msgs/CMakeLists.txt
sensor_msgs/msg/BatteryState.msg
std_srvs/CMakeLists.txt
std_srvs/srv/SetBool.srv

Connects to https://github.com/ros2/common_interfaces/issues/27
Closes https://github.com/ros2/common_interfaces/issues/27
This PR doesn't include `SetBool.srv` from `std_srvs` to follow the "services names should carry semantic meaning" guideline

port missing interfaces from ROS1 common_msgs

---

sensor_msgs/CMakeLists.txt
sensor_msgs/package.xml

We enable all of the linters except for the copyright one,
which doesn't understand BSD right now.  All of the other
tests pass.
Signed-off-by: Chris Lalancette <clalancette@osrfoundation.org>
Fixes ros2/common_interfaces#32

Reenable linting in sensor_msgs.

---

sensor_msgs/CMakeLists.txt
sensor_msgs/include/sensor_msgs/impl/point_cloud2_iterator.hpp
sensor_msgs/include/sensor_msgs/point_cloud2_iterator.hpp

connects to ros2/ros2#342
CI:
linux: [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_turtlebot-demo_linux&build=8)](http://ci.ros2.org/job/ci_turtlebot-demo_linux/8/)

Add in a ported implementation of the PointCloud2Iterator.

---

common_interfaces/CMakeLists.txt
common_interfaces/package.xml

this came up a few times and more often since we started shipping binaries.
Creating this metapackage has 2 benefits:
- allow people to install all common message packages with a single debian package
- show an example of how metapackages look like in ROS2
One remaining question though: we renamed all message packages from `foo_interfaces` to `foo_msgs` a while ago to simplify the mapping between ros1 and ros2 messages. Should this package be named common_msgs like its' ROS1 equivalent? If so should we also rename this repository accordingly ?

create common_interfaces metapackage

---

actionlib_msgs/package.xml
diagnostic_msgs/package.xml
geometry_msgs/package.xml
nav_msgs/package.xml
sensor_msgs/package.xml
shape_msgs/package.xml
std_msgs/package.xml
std_srvs/package.xml
stereo_msgs/package.xml
trajectory_msgs/package.xml
visualization_msgs/package.xml

Follow-up of https://github.com/ament/ament_tools/pull/168.
Opening this to gather feedback as of how we should call the group containing ros IDL files.
This PR uses `interface_packages` but I'm open to alternatives

member of rosidl_interfaces_packages group

---

rosgraph_msgs/CMakeLists.txt
rosgraph_msgs/msg/Clock.msg
rosgraph_msgs/package.xml

Fixes ros2/ros1_bridge#104. Connect to ros2/ros1_bridge#104.
This adds the `Clock` message from the [rosgraph_msgs](https://github.com/ros/ros_comm_msgs/blob/indigo-devel/rosgraph_msgs) package.
The other two messages fro ROS 1 seem to not have a 1-to-1 equivalent in ROS 2 therefore I didn't add them at this point.

add rosgraph_msgs package with Clock message

---

sensor_msgs/include/sensor_msgs/impl/point_cloud2_iterator.hpp

Prevents the following compile error when using the header:
~~~
/opt/ros/bouncy/include/sensor_msgs/impl/point_cloud2_iterator.hpp:73:23: error: aggregate 'std::stringstream err' has incomplete type and cannot be defined
std::stringstream err;
^~~
~~~

Include sstream on header that needs it

---

sensor_msgs/include/sensor_msgs/fill_image.hpp

Port fill image header from ROS 1.
I'm using this on `gazebo_plugins/gazebo_ros_camera`.
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=5164)](http://ci.ros2.org/job/ci_linux/5164/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=1940)](http://ci.ros2.org/job/ci_linux-aarch64/1940/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=4290)](http://ci.ros2.org/job/ci_osx/4290/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=5144)](http://ci.ros2.org/job/ci_windows/5144/)

Fill image

---

actionlib_msgs/CMakeLists.txt
diagnostic_msgs/CMakeLists.txt
geometry_msgs/CMakeLists.txt
nav_msgs/CMakeLists.txt
sensor_msgs/CMakeLists.txt
shape_msgs/CMakeLists.txt
std_msgs/CMakeLists.txt
std_srvs/CMakeLists.txt
stereo_msgs/CMakeLists.txt
trajectory_msgs/CMakeLists.txt
visualization_msgs/CMakeLists.txt

We can now compile the C generated code with -Wpedantic (see https://github.com/ros2/ros2/issues/567#issuecomment-420344685 for additional context).
I have a similar commits for all message packages, I am planning on getting the changes reviewed here and then push the other identical commits directly.
This does **not** supersede the work from https://github.com/ros2/ros2/issues/567 that will eventually replace the way compile options are passed, but I figured I'd open this as I already had all the changes to confirm that https://github.com/ros2/rosidl_python/pull/10 allowed us to compile with pedantic.
Below CI for all the `add_compile_options` branches.
None:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=5208)](http://ci.ros2.org/job/ci_linux/5208/)
* …

use add_compile_options instead of setting only cxx flags

---

visualization_msgs/CMakeLists.txt
visualization_msgs/srv/GetInteractiveMarkers.srv

This service is meant to replace use of InteractiveMarkerInit.msg on a latched topic.
Connects to https://github.com/ros-visualization/interactive_markers/issues/42

Add GetInteractiveMarkers.srv

---

actionlib_msgs/README.md
actionlib_msgs/package.xml

Related to https://github.com/ros2/common_interfaces/issues/64
If there's better mechanism for signaling the deprecation of a package, please advise.

Add notice that actionlib_msgs is deprecated

---

geometry_msgs/msg/Quaternion.msg

It was often a gotcha in ROS1 that creating a default `Quaternion` object didn't give you the identity quaternion (`w,x,y,z == 1,0,0,0`) but rather an invalid quaternion with everything initialized to zero. I always thought this was the perfect use of default values in the `.msg` file. Any particular reason why this hasn't been done already?

Make Quaternion valid by default

---

sensor_msgs/include/sensor_msgs/image_encodings.hpp
sensor_msgs/test/test_image_encodings.cpp

This adds the YUY2/YUYV version of the YUV 4:2:2 image encoding, as discussed in #76 .
I chose the name `YUV422_YUY2`, to use the most popular fourcc code `YUY2` and try to be consistent with the existing `YUV422` encoding.

Add the YUY2 image encoding

---

common_interfaces/CMakeLists.txt
common_interfaces/package.xml

Included ament_lint_common and ament_lint_auto as test dependencies
Signed-off-by: Jorge J. Perez <jjperez@ekumenlabs.com>

Add common linters as test dependencies

---

sensor_msgs/include/sensor_msgs/point_cloud_conversion.hpp
sensor_msgs/msg/PointCloud.msg
sensor_msgs/test/test_pointcloud_conversion.cpp

Fixes #105 
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=10152)](http://ci.ros2.org/job/ci_linux/10152/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=5720)](http://ci.ros2.org/job/ci_linux-aarch64/5720/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=8256)](http://ci.ros2.org/job/ci_osx/8256/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=10046)](http://ci.ros2.org/job/ci_windows/10046/)

Deprecate PointCloud message and APIs using it

---

std_msgs/msg/Bool.msg
std_msgs/msg/Byte.msg
std_msgs/msg/ByteMultiArray.msg
std_msgs/msg/Char.msg
std_msgs/msg/Float32.msg
std_msgs/msg/Float32MultiArray.msg
std_msgs/msg/Float64.msg
std_msgs/msg/Float64MultiArray.msg
std_msgs/msg/Int16.msg
std_msgs/msg/Int16MultiArray.msg
std_msgs/msg/Int32.msg
std_msgs/msg/Int32MultiArray.msg
std_msgs/msg/Int64.msg
std_msgs/msg/Int64MultiArray.msg
std_msgs/msg/Int8.msg
std_msgs/msg/Int8MultiArray.msg
std_msgs/msg/MultiArrayDimension.msg
std_msgs/msg/MultiArrayLayout.msg
std_msgs/msg/String.msg
std_msgs/msg/UInt16.msg
std_msgs/msg/UInt16MultiArray.msg
std_msgs/msg/UInt32.msg
std_msgs/msg/UInt32MultiArray.msg
std_msgs/msg/UInt64.msg
std_msgs/msg/UInt64MultiArray.msg
std_msgs/msg/UInt8.msg
std_msgs/msg/UInt8MultiArray.msg

Add deprecation messages to all messages now in example_interfaces

---

visualization_msgs/msg/ImageMarker.msg
visualization_msgs/msg/Marker.msg

This is a follow up to the [Aggregate Foxy Message API Review](https://github.com/ros2/common_interfaces/pull/86)
In both Marker and ImageMarker the constants are all uint8
https://github.com/ros2/common_interfaces/blob/519e851f6ac71262e45b6e5ca66bce653a72948d/visualization_msgs/msg/ImageMarker.msg#L1-L8
However the action and type they are used in are int32
https://github.com/ros2/common_interfaces/blob/519e851f6ac71262e45b6e5ca66bce653a72948d/visualization_msgs/msg/ImageMarker.msg#L15-L18
This proposes to homogenize them by changing the const's declared type to be consistent.

Homogenize const types with usage in action and type storage

---

geometry_msgs/msg/TransformStamped.msg

Improve documentation for TransformStamped.msg

---

nav_msgs/msg/GridCells.msg
nav_msgs/msg/MapMetaData.msg
nav_msgs/msg/OccupancyGrid.msg

Add comments for nav_msgs defintions

---

geometry_msgs/msg/InertiaStamped.msg
geometry_msgs/msg/Point32.msg
geometry_msgs/msg/TransformStamped.msg
nav_msgs/msg/GridCells.msg
nav_msgs/msg/Odometry.msg
nav_msgs/msg/Path.msg
nav_msgs/srv/GetMap.srv
nav_msgs/srv/GetPlan.srv
nav_msgs/srv/SetMap.srv
trajectory_msgs/msg/JointTrajectory.msg
trajectory_msgs/msg/JointTrajectoryPoint.msg
trajectory_msgs/msg/MultiDOFJointTrajectoryPoint.msg

This adds API documentation to each message and service that didn't already have them.

Finish up API documentation

---

sensor_msgs/include/sensor_msgs/fill_image.hpp

While running the ABI checker on this package it complains about memcpy not being declared. I'm including here the <cstring> header and use the std namespace.

Missing cstring header for memcpy in fill_image.hpp

---

diagnostic_msgs/QUALITY_DECLARATION.md
diagnostic_msgs/README.md
geometry_msgs/QUALITY_DECLARATION.md
geometry_msgs/README.md
nav_msgs/QUALITY_DECLARATION.md
sensor_msgs/QUALITY_DECLARATION.md
sensor_msgs/README.md
shape_msgs/QUALITY_DECLARATION.md
shape_msgs/README.md
std_msgs/QUALITY_DECLARATION.md
std_msgs/README.md
std_srvs/QUALITY_DECLARATION.md
std_srvs/README.md
stereo_msgs/QUALITY_DECLARATION.md
stereo_msgs/README.md
trajectory_msgs/QUALITY_DECLARATION.md
visualization_msgs/QUALITY_DECLARATION.md

Update QDs to QL 1

---

sensor_msgs_py/LICENSE
sensor_msgs_py/package.xml
sensor_msgs_py/pytest.ini
sensor_msgs_py/sensor_msgs_py/point_cloud2.py
sensor_msgs_py/setup.cfg
sensor_msgs_py/setup.py
sensor_msgs_py/test/test_copyright.py
sensor_msgs_py/test/test_flake8.py
sensor_msgs_py/test/test_pep257.py
sensor_msgs_py/test/test_point_cloud2.py

Hi, 
The python submodule `point_cloud2` in ROS1 was useful when working with `PointCloud2` messages. 
[People](https://answers.ros.org/question/357944/why-is-point_cloud2py-missing-from-sensor_msgs-in-ros2/) including me would like this feature in ROS2, so I took the opportunity to "port" it.
This is the first time I ever perform a PR to a significant project, and I've tried to follow the developer guidelines to the best of my abilities. Neverthessless, I've probably made some mistakes. 
**Tests:**  
Not all tests are passing. 
```
The following tests FAILED:
27 - flake8_rosidl_generated_py (Failed)
34 - flake8 (Failed)
36 - copyright (Failed)
```
The two former seem to not be related to this package per se, but rather to `flake8` [link](https://gitlab.com/pycqa/flake8/-/issues/640). …

Port of point_cloud2.py from ROS1 to ROS2.

---

sensor_msgs/include/sensor_msgs/point_cloud2_iterator.hpp

The class PointCloud2Iterator isn't in the `msg` namespace, fixed the example in the comments

Fix PointCloud2Iterator namespacing in docs

---

sensor_msgs/include/sensor_msgs/fill_image.hpp

On Dashing, you cannot `#include <sensor_msgs/fill_image.hpp>` due to a call to `memcpy` without the `<cstring>` header declaring it. This was fixed already in Foxy in #125 (and `master` in #126); this just cherry-picks that fix into the `dashing` branch.

Backport fix for sensor_msgs/fill_image.hpp missing header to Dashing #125 

---

sensor_msgs_py/setup.cfg

To avoid an user-warning when building
https://ci.ros2.org/view/nightly/job/nightly_linux_release/1890/consoleFull#console-section-382

Use underscores instead of dashes in setup.cfg

---

sensor_msgs/msg/CompressedImage.msg

Should be merged after https://github.com/ros-perception/image_transport_plugins/pull/75.

Update CompressedImage documentation: add 'tiff' as a supported format

---

sensor_msgs/CMakeLists.txt

This should fix the warnings in CI. I pushed the branch, but forgot to open a PR. That's why CI in ros2/rosidl#606 passed. Since this has already been tested in CI I think it just needs an approving review.

Use rosidl_get_typesupport_target()

---

sensor_msgs/include/sensor_msgs/distortion_models.hpp

This is a forward-port from ROS1 noetic:
https://github.com/ros/common_msgs/pull/109
This PR brings the ROS2 list of supported distortion models back into sync with ROS Noetic and is required to forward-port support for this model in vision_opencv:
https://github.com/ros-perception/vision_opencv/pull/358
----------------------------------------------------------------------
*Background info*
The model is based on the following publication:
J. Kannala and S. Brandt (2006). A Generic Camera Model and Calibration Method for Conventional, Wide-Angle, and Fish-Eye Lenses, IEEE Transactions on Pattern Analysis and Machine Intelligence, vol. 28, no.  8, pp. 1335-1340
There are many different names for this distortion model:
* Kannala and Brandt call it "Generic Camera Model". Sometimes they also …

Add equidistant distortion model

---

sensor_msgs/include/sensor_msgs/distortion_models.hpp
sensor_msgs/include/sensor_msgs/fill_image.hpp
sensor_msgs/include/sensor_msgs/image_encodings.hpp
sensor_msgs/include/sensor_msgs/impl/point_cloud2_iterator.hpp
sensor_msgs/include/sensor_msgs/point_cloud2_iterator.hpp
sensor_msgs/include/sensor_msgs/point_cloud_conversion.hpp
sensor_msgs/include/sensor_msgs/point_field_conversion.hpp
sensor_msgs/test/test_image_encodings.cpp
sensor_msgs/test/test_pointcloud_iterator.cpp

This was propagated due to an invalid license in ament_lint which is proposed to be fixed at: https://github.com/ament/ament_lint/pull/209

Cleanup mislabeled BSD license

---

shape_msgs/msg/SolidPrimitive.msg

This feature adds a `geometry_msgs::msg::Polygon` field to the [shape_msgs/msg/SolidPrimitive.msg](https://github.com/ros2/common_interfaces/blob/master/shape_msgs/msg/SolidPrimitive.msg) in order to represent `PRISM` primitive too.
Explained in detail in #166

Add prism type to the SolidPrimitive.msg (#166)

---

sensor_msgs/include/sensor_msgs/image_encodings.hpp

https://www.kernel.org/doc/html/latest/userspace-api/media/v4l/pixfmt-yuv-planar.html
Adding V4L2_PIX_FMT_NV12 (YUV420) and V4L2_PIX_FMT_NV24 (YUV444) formats to image encodings to facilitate hardware accelerator support.

Add YUV420 and YUV444 to image encodings

---

actionlib_msgs/package.xml
diagnostic_msgs/package.xml
geometry_msgs/package.xml
nav_msgs/package.xml
sensor_msgs/package.xml
shape_msgs/package.xml
std_msgs/package.xml
stereo_msgs/package.xml
trajectory_msgs/package.xml
visualization_msgs/package.xml

It seems that the interface packages are missing a `<build_export_depend>` tag for the interface packages that they depend on. The build export dependency is important because downstream packages need to know about the upstream interface dependencies at build time, e.g. to have access to the headers of the upstream interface packages. The lack of this tag made it impossible for [`rosidl_generator_rs`](https://github.com/ros2-rust/ros2_rust/tree/master/rosidl_generator_rs) to correctly identify the build dependency tree for the message packages.
But also, adding `<build_export_depend>` onto the already existing `<build_depend>` and `<exec_depend>` tags is the same as just specifying the `<depend>` tag, so this PR simplifies all the depend tags to just `<depend>`.

Interface packages should fully <depend> on the interface packages that they depend on

---

sensor_msgs/CMakeLists.txt

This adds a modern CMake target `sensor_msgs_library` usable downstream as sensor_msgs::sensor_msgs_library and installs headers to a unique include directory as part of ros2/ros2#1150
It might depend on ros2/rosidl#662, I'm not sure.

Add sensor_msgs_library target and install headers to include/${PROJECT_NAME}

---

sensor_msgs/README.md

Signed-off-by: Homalozoa <nx.tardis@gmail.com>

[Fix] Fix image_encodings.hpp's URL in README

---

.gitignore
sensor_msgs_py/package.xml
sensor_msgs_py/sensor_msgs_py/point_cloud2.py
sensor_msgs_py/test/test_point_cloud2.py

This pull request ports the `PointCloud` creation to NumPy. It should massively increase the performance for large point clouds as no iteration over the points in python is needed and the bytes are taken directly from NumPy.
Still needs some work regarding other field types. Feel free to comment on my implementation. Suggestions are welcome.
Cheers

Port pointcloud creation to numpy.

---

shape_msgs/msg/SolidPrimitive.msg

Follow up from https://github.com/ros2/common_interfaces/pull/167
In my previous PR I was supposed to add a single `geometry_msgs::msg::Polygon` to the message but I've added an array of it by mistake :man_facepalming: 
It's even a part of humble now :(
This PR fixes it.

Fix SolidPrimitive.msg to contain a single Polygon

---

sensor_msgs/include/sensor_msgs/impl/point_cloud2_iterator.hpp
sensor_msgs/include/sensor_msgs/point_cloud2_iterator.hpp
sensor_msgs/test/test_pointcloud_iterator.cpp

Reopen a pull request for the master branch. The width and height were modified after this resize call. Now the width and height will be retained if they were set before. A new method is also provided to input the set width and height.
Signed-off-by: tonylitianyu <tonylitianyu@gmail.com>

retain width and height after resize for master

---

sensor_msgs/include/sensor_msgs/impl/point_cloud2_iterator.hpp
sensor_msgs/include/sensor_msgs/point_cloud2_iterator.hpp
sensor_msgs/test/test_pointcloud_iterator.cpp

cast size_t to uint32_t to resolve msbuild warning
Signed-off-by: tonylitianyu <tonylitianyu@gmail.com>

Cast to uint32_t for pointcloud2 resize method

---

sensor_msgs_py/sensor_msgs_py/point_cloud2.py

Remove reference to old implementation and port of said implementation, as the file has been rewritten from scratch since then.
Not high priority, but the reference might cause some confusion and is definitely outdated. Other suggesting regarding a rewording instead of the removal are welcome.

Remove reference to old implementation

---

sensor_msgs/include/sensor_msgs/image_encodings.hpp

@clalancette Would you mind reviewing because this is a ``// TODO(clalancette)``?
I'm guessing we should keep ``ABSTRACT_ENCODING_PREFIXES`` there in case it's being used by others downstream.

use regex for matching cv types

---

sensor_msgs_py/sensor_msgs_py/point_cloud2.py
sensor_msgs_py/test/test_point_cloud2.py

Add support for non standard point step sizes

---

sensor_msgs/include/sensor_msgs/image_encodings.hpp

[NV21](https://www.kernel.org/doc/html/v4.10/media/uapi/v4l/pixfmt-nv12.html) and [NV24](https://www.kernel.org/doc/html/v4.10/media/uapi/v4l/pixfmt-nv24.html) are colour formats according to the kernel documentation. This PR adds them to the list of formats for which `isColor()` returns true.

Add NV21 and NV24 to colour formats

---

actionlib_msgs/CMakeLists.txt
diagnostic_msgs/CMakeLists.txt
geometry_msgs/CMakeLists.txt
nav_msgs/CMakeLists.txt
sensor_msgs/CMakeLists.txt
shape_msgs/CMakeLists.txt
std_msgs/CMakeLists.txt
std_srvs/CMakeLists.txt
stereo_msgs/CMakeLists.txt
trajectory_msgs/CMakeLists.txt
visualization_msgs/CMakeLists.txt

The main reason to do this is so that we can compile common_interfaces with the clang static analyzer. As of clang++-14 (what is in Ubuntu 22.04), the default still seems to be C++14, so we need to specify C++17 so that new things in the rclcpp headers work properly.
Further, due to reasons I don't fully understand, I needed to set CMAKE_CXX_STANDARD_REQUIRED in order for clang to really use that version. So set this as well.

Update common_interfaces to C++17.

---

sensor_msgs_py/package.xml

Fix missing `exec_depends` in `package.xmls` to generate documentation without any warnings using `autodoc`

Enable document generation using rosdoc2 for ament_python pkgs

---

sensor_msgs/msg/Range.msg

Fixes #180
As stated in the original issue, the Range msg lacks the variance field as opposed to most sensor msgs.
A similar issue exist for ros1, and here the discussion about it: https://github.com/ros/common_msgs/issues/142

sensor_msgs/Range lacks variance field

---

sensor_msgs/include/sensor_msgs/image_encodings.hpp

The YUV formats seem to be ambiguous. With this PR, I would like to clarify this and properly document their memory layout. There is no "yuv422_yuy2" format and the "yuv422" format refers to the format code `YU16`. The documentation mentions a "UYUV" format, which does not exist. Additionally, the website http://www.fourcc.org is not reachable anymore.
With the wayback machine, I compared the documented memory layout from http://www.fourcc.org with the one from the Linux kernel documentation from https://www.kernel.org/doc/html/latest/. I found that for the `yuv422` the memory layout described at [fourcc.org](https://web.archive.org/web/20210316221649/https://www.fourcc.org/pixel-format/yuv-uyvy/) matches `V4L2_PIX_FMT_UYVY` at [kernel.org](https://www.kernel.org/doc/html/latest/userspace- …

update YUV format codes and documentation

---

sensor_msgs_py/sensor_msgs_py/point_cloud2.py
sensor_msgs_py/test/test_point_cloud2.py

The current `point_cloud2.read_points_numpy` function takes a pointcloud2 message and returns an unstructured numpy array of the points.
There is an assertion test that all fields are the same data type, required for unstructured numpy arrays.
However if you have multiple data types and use the `field_names` parameter to select only a certain subset of fields with a matching data type, all fields are still tested for the same data type and this will fail.
Change fixes this so that if you are using "field_names", only checks the selected fields have matching data types.
Includes a test case to verify that a call with non-uniform field types fails, and a test case for selecting fields with matching types works even when dissimilar types exist in the pointcloud.

Fix read_points_numpy field_names parameter

---

sensor_msgs/msg/CompressedImage.msg

Port of https://github.com/ros/common_msgs/pull/184 to ROS 2.
From original PR:
> 
> The description of the format field has long been outdated. This PR fixes it to be up-to-date with the core image_transport plugins.
>

sensor_msgs/CompressedImage: updated description of format field

---

sensor_msgs/CMakeLists.txt

Follow up from https://github.com/ros-geographic-info/geographic_info/pull/56#discussion_r1505260952, where I recommend we check this condition based on the `TARGET` keyword. We are expecting a target, not a non-zero length string, so it better expresses intent.
I would like to set the precedent for it here, and then perhaps update the ROS tutorial on this feature.

Use target qualifier for checking the cpp typesupport exists

---

visualization_msgs/msg/Marker.msg

This is a rebase of #218 for a clean merge from @rr-tom-noble but since it's been queued so long it's out of date. 
There's a partial implementation in https://github.com/ros2/rviz/pull/972
However I would suggest that we land this in rolling to both keep it in sync with the ROS 1 version that's already added this. And to enable the use of the message with other implementations in the future. If we don't add this now it won't be able to be added for another year.

Adds ARROW_STRIP to Marker.msg

---

sensor_msgs/include/sensor_msgs/image_encodings.hpp
sensor_msgs/test/test_image_encodings.cpp

https://github.com/ros2/common_interfaces/pull/214 introduced new encoding names `uyvy` and `yuyv` as replacement for `yuv422` and `yuv422_yuy2`. This PR marks those replaced encodings as deprecated with a hint which encoding to use instead and removes their usage in this repo.

mark YUV encodings as deprecated

---

sensor_msgs/include/sensor_msgs/image_encodings.hpp
sensor_msgs/test/test_image_encodings.cpp

Reverts ros2/common_interfaces#247
This is causing numerous problems throughout the codebase, and on Windows.

Revert "mark YUV encodings as deprecated"

---

sensor_msgs/include/sensor_msgs/image_encodings.hpp

I propose this PR to enable ROS2 support of NV12 pixel format as image encoding. The NV12 pixel format is a common output format of hardware-accelerated decoders. NV12 is quite similar to the NV21 pixel format, with the exception that the order of the interleaving of U and V is reversed. The hardware-accelerated video decoder I currently use only supports NV12 as output pixel format. 
NV12 corresponds to the [FourCC](https://fourcc.org/pixel-format/yuv-nv12/), which was previously recommended as the identifier (see also #204 and #214).
The image_encodings.hpp file has been extended with the necessary additions. 
References to show unambiguousness of the NV12 pixel format:
- V4L2: https://github.com/torvalds/linux/blob/v5.19/include/uapi/linux/videodev2.h#L599
- Kernel: …

Add NV12 to pixel formats
