ros2/common_interfaces

actionlib_interfaces/CMakeLists.txt, builtin_interfaces/CMakeLists.txt, diagnostics_interfaces/CMakeLists.txt, geometry_interfaces/CMakeLists.txt, nav_interfaces/CMakeLists.txt, sensor_interfaces/CMakeLists.txt, shape_interfaces/CMakeLists.txt, std_interfaces/CMakeLists.txt, stereo_interfaces/CMakeLists.txt, trajectory_interfaces/CMakeLists.txt, visualization_interfaces/CMakeLists.txt
=> raise warning level

sensor_interfaces/msg/CameraInfo.msg, stereo_interfaces/msg/DisparityImage.msg
=> apply changes to adhere to stricter field name rules

sensor_msgs/CMakeLists.txt
=> re-enable Joy.msg

actionlib_msgs/CMakeLists.txt, actionlib_msgs/package.xml, builtin_interfaces/CMakeLists.txt, builtin_interfaces/package.xml, diagnostic_msgs/CMakeLists.txt, diagnostic_msgs/package.xml, geometry_msgs/CMakeLists.txt, geometry_msgs/package.xml, nav_msgs/CMakeLists.txt, nav_msgs/package.xml, sensor_msgs/CMakeLists.txt, sensor_msgs/package.xml, shape_msgs/CMakeLists.txt, shape_msgs/package.xml, std_msgs/CMakeLists.txt, std_msgs/package.xml, std_srvs/CMakeLists.txt, std_srvs/package.xml, stereo_msgs/CMakeLists.txt, stereo_msgs/package.xml, trajectory_msgs/CMakeLists.txt, trajectory_msgs/package.xml, visualization_msgs/CMakeLists.txt, visualization_msgs/package.xml
=> Get rosidl to add linter tests for generated interface code

actionlib_msgs/CMakeLists.txt, builtin_interfaces/CMakeLists.txt, diagnostic_msgs/CMakeLists.txt, geometry_msgs/CMakeLists.txt, nav_msgs/CMakeLists.txt, sensor_msgs/CMakeLists.txt, shape_msgs/CMakeLists.txt, std_msgs/CMakeLists.txt, std_srvs/CMakeLists.txt, stereo_msgs/CMakeLists.txt, trajectory_msgs/CMakeLists.txt, visualization_msgs/CMakeLists.txt
Connect to ament/ament_cmake#72
=> require CMake 3.5

geometry_msgs/CMakeLists.txt, sensor_msgs/CMakeLists.txt, std_msgs/CMakeLists.txt
TODOs not needed since https://github.com/ros2/common_interfaces/pull/23
=> remove todos

actionlib_msgs/CMakeLists.txt, builtin_interfaces/CMakeLists.txt, diagnostic_msgs/CMakeLists.txt, geometry_msgs/CMakeLists.txt, nav_msgs/CMakeLists.txt, sensor_msgs/CMakeLists.txt, shape_msgs/CMakeLists.txt, std_msgs/CMakeLists.txt, std_srvs/CMakeLists.txt, stereo_msgs/CMakeLists.txt, trajectory_msgs/CMakeLists.txt, visualization_msgs/CMakeLists.txt
see https://github.com/ros2/ros2/issues/305#issuecomment-283601977
=> add Wpedantic flag

sensor_msgs/CMakeLists.txt, sensor_msgs/include/sensor_msgs/distortion_models.hpp, sensor_msgs/include/sensor_msgs/impl/point_cloud2_iterator.hpp, sensor_msgs/include/sensor_msgs/point_cloud2_iterator.hpp
addresses https://github.com/ament/ament_lint/pull/73#issuecomment-300580964
Fixes https://github.com/ros2/common_interfaces/issues/35
=> [sensor_msgs] Reenable copyright test

sensor_msgs/include/sensor_msgs/distortion_models.hpp, sensor_msgs/include/sensor_msgs/impl/point_cloud2_iterator.hpp, sensor_msgs/include/sensor_msgs/point_cloud2_iterator.hpp
Signed-off-by: Chris Lalancette <clalancette@osrfoundation.org>
=> Add a comment saying where distortion_model.hpp originally came from.

sensor_msgs/include/sensor_msgs/image_encodings.hpp
=> Add image_encodings.hpp

actionlib_msgs/package.xml, common_interfaces/package.xml, diagnostic_msgs/package.xml, geometry_msgs/package.xml, nav_msgs/package.xml, sensor_msgs/package.xml, shape_msgs/package.xml, std_msgs/package.xml, std_srvs/package.xml, stereo_msgs/package.xml, trajectory_msgs/package.xml, visualization_msgs/package.xml
Fast-forward onto master if approved.
=> Prepare 0.5.0

actionlib_msgs/package.xml, common_interfaces/CMakeLists.txt, common_interfaces/package.xml, diagnostic_msgs/package.xml, geometry_msgs/package.xml, nav_msgs/package.xml, sensor_msgs/include/sensor_msgs/impl/point_cloud2_iterator.hpp, sensor_msgs/package.xml, shape_msgs/package.xml, std_msgs/package.xml, std_srvs/package.xml, stereo_msgs/package.xml, trajectory_msgs/package.xml, visualization_msgs/package.xml
=> Fast forward 'bouncy' branch to current master for Bouncy patch 2 release

sensor_msgs/include/sensor_msgs/impl/point_cloud2_iterator.hpp, sensor_msgs/include/sensor_msgs/point_cloud2_iterator.hpp
Some issues with the doxygen generation that were pointed out to me.
=> replace use of PRE tags with \verbatim in doxygen

sensor_msgs/msg/BatteryState.msg
Essentially a cherry-pick of https://github.com/ros/common_msgs/pull/140
onto ROS 2.
=> Add temperature to the BatteryState message.

actionlib_msgs/package.xml
I'm not going to run CI since it is just a change to the package.xml description.
=> Fix a simple typo in the description.

sensor_msgs/msg/CameraInfo.msg, sensor_msgs/msg/Image.msg
Reference the correct header files.
Connects to #3
=> Update message documentation

sensor_msgs/include/sensor_msgs/image_encodings.hpp, sensor_msgs/include/sensor_msgs/impl/point_cloud2_iterator.hpp, sensor_msgs/include/sensor_msgs/point_cloud_conversion.hpp
Style update to match the ROS 2 development guide and pass with the updated linter configuration from ament/ament_lint#210.
=> code style only: wrap after open parenthesis if not in one line

diagnostic_msgs/QUALITY_DECLARATION.md, diagnostic_msgs/README.md, diagnostic_msgs/msg/KeyValue.msg, geometry_msgs/QUALITY_DECLARATION.md, geometry_msgs/README.md, geometry_msgs/msg/Inertia.msg, nav_msgs/QUALITY_DECLARATION.md, nav_msgs/README.md, nav_msgs/msg/MapMetaData.msg, sensor_msgs/QUALITY_DECLARATION.md, sensor_msgs/README.md, sensor_msgs/msg/JoyFeedback.msg, shape_msgs/QUALITY_DECLARATION.md, shape_msgs/README.md, std_msgs/QUALITY_DECLARATION.md, std_msgs/README.md, std_srvs/QUALITY_DECLARATION.md, std_srvs/README.md, stereo_msgs/QUALITY_DECLARATION.md, stereo_msgs/README.md, trajectory_msgs/QUALITY_DECLARATION.md, trajectory_msgs/README.md, visualization_msgs/QUALITY_DECLARATION.md, visualization_msgs/README.md, visualization_msgs/msg/InteractiveMarker.msg, visualization_msgs/msg/InteractiveMarkerFeedback.msg, visualization_msgs/msg/InteractiveMarkerInit.msg
Adding Quality Declarations for each package with the current QL of 4.
Depends on #108 
New commit: b3f47837b1aceda17e437bb0187ca65e18646a9d
=> Add current-level quality declarations

sensor_msgs/msg/PointField.msg
Using values found in laser_geometry and depth_image_proc
For #106
=> Comment on common PointField names

sensor_msgs/msg/MultiDOFJointState.msg
=> Improve clarification of MultiDOFJointState

geometry_msgs/msg/Vector3.msg, geometry_msgs/msg/Vector3Stamped.msg
=> Clarify vector semantics

diagnostic_msgs/QUALITY_DECLARATION.md, geometry_msgs/QUALITY_DECLARATION.md, nav_msgs/QUALITY_DECLARATION.md, sensor_msgs/QUALITY_DECLARATION.md, shape_msgs/QUALITY_DECLARATION.md, std_msgs/QUALITY_DECLARATION.md, std_srvs/QUALITY_DECLARATION.md, stereo_msgs/QUALITY_DECLARATION.md, trajectory_msgs/QUALITY_DECLARATION.md, visualization_msgs/QUALITY_DECLARATION.md
Improved descriptions for Version Stability
Signed-off-by: ahcorde <ahcorde@gmail.com>
=> QD Update Version Stability to stable version

diagnostic_msgs/QUALITY_DECLARATION.md, geometry_msgs/QUALITY_DECLARATION.md, nav_msgs/QUALITY_DECLARATION.md, sensor_msgs/QUALITY_DECLARATION.md, shape_msgs/QUALITY_DECLARATION.md, std_msgs/QUALITY_DECLARATION.md, std_srvs/QUALITY_DECLARATION.md, stereo_msgs/QUALITY_DECLARATION.md, trajectory_msgs/QUALITY_DECLARATION.md, visualization_msgs/QUALITY_DECLARATION.md
This PR adds a link to REP-2006 (the Security Vulnerability Declaration) to the Quality Declaration for this repository.
Connects to ros2/ros2#924.
=> QD Security Vulnerability Declaration: REP 2006

diagnostic_msgs/QUALITY_DECLARATION.md, diagnostic_msgs/README.md, geometry_msgs/QUALITY_DECLARATION.md, geometry_msgs/README.md, nav_msgs/QUALITY_DECLARATION.md, nav_msgs/README.md, sensor_msgs/QUALITY_DECLARATION.md, sensor_msgs/README.md, shape_msgs/QUALITY_DECLARATION.md, shape_msgs/README.md, std_msgs/QUALITY_DECLARATION.md, std_msgs/README.md, std_srvs/QUALITY_DECLARATION.md, std_srvs/README.md, stereo_msgs/QUALITY_DECLARATION.md, stereo_msgs/README.md, trajectory_msgs/QUALITY_DECLARATION.md, trajectory_msgs/README.md, visualization_msgs/QUALITY_DECLARATION.md, visualization_msgs/README.md
=> Update Quality levels to level 3

sensor_msgs/include/sensor_msgs/fill_image.hpp
=> Missing cstring header for memcpy in fill_image.hpp

nav_msgs/CMakeLists.txt, nav_msgs/srv/LoadMap.srv
Analog to https://github.com/ros/common_msgs/pull/152
CC @jacobperron @tfoote
=> Add LoadMap service definition

diagnostic_msgs/QUALITY_DECLARATION.md, diagnostic_msgs/README.md, geometry_msgs/QUALITY_DECLARATION.md, geometry_msgs/README.md, nav_msgs/QUALITY_DECLARATION.md, nav_msgs/README.md, sensor_msgs/QUALITY_DECLARATION.md, sensor_msgs/README.md, shape_msgs/QUALITY_DECLARATION.md, shape_msgs/README.md, std_msgs/QUALITY_DECLARATION.md, std_msgs/README.md, std_srvs/QUALITY_DECLARATION.md, std_srvs/README.md, stereo_msgs/QUALITY_DECLARATION.md, stereo_msgs/README.md, trajectory_msgs/QUALITY_DECLARATION.md, trajectory_msgs/README.md, visualization_msgs/QUALITY_DECLARATION.md, visualization_msgs/README.md
Updated Quality Level to 2:
- std_srvs
- common_interfaces
- geometry_msgs
- sensor_msgs
- stereo_msgs
- shape_msgs   
- trajectory_msgs
- diagnostic_msgs
- nav_msgs
- std_msgs
- visualization_msgs
Signed-off-by: ahcorde <ahcorde@gmail.com>
=> Updated Quality Level to 2

actionlib_msgs/package.xml, common_interfaces/package.xml, diagnostic_msgs/package.xml, geometry_msgs/package.xml, nav_msgs/package.xml, sensor_msgs/package.xml, shape_msgs/package.xml, std_msgs/package.xml, std_srvs/package.xml, stereo_msgs/package.xml, trajectory_msgs/package.xml, visualization_msgs/package.xml
Precisely what the title says.
=> Update package maintainers.

diagnostic_msgs/QUALITY_DECLARATION.md, diagnostic_msgs/README.md, geometry_msgs/QUALITY_DECLARATION.md, geometry_msgs/README.md, nav_msgs/QUALITY_DECLARATION.md, sensor_msgs/QUALITY_DECLARATION.md, sensor_msgs/README.md, shape_msgs/QUALITY_DECLARATION.md, shape_msgs/README.md, std_msgs/QUALITY_DECLARATION.md, std_msgs/README.md, std_srvs/QUALITY_DECLARATION.md, std_srvs/README.md, stereo_msgs/QUALITY_DECLARATION.md, stereo_msgs/README.md, trajectory_msgs/QUALITY_DECLARATION.md, visualization_msgs/QUALITY_DECLARATION.md
=> [foxy] Update QDs to QL 1 (#135)

sensor_msgs/QUALITY_DECLARATION.md
This will also need to be backported to foxy
=> Add coverage/performance to qd for sensor_msgs

diagnostic_msgs/QUALITY_DECLARATION.md, geometry_msgs/QUALITY_DECLARATION.md, nav_msgs/QUALITY_DECLARATION.md, sensor_msgs/QUALITY_DECLARATION.md, shape_msgs/QUALITY_DECLARATION.md, std_msgs/QUALITY_DECLARATION.md, std_srvs/QUALITY_DECLARATION.md, stereo_msgs/QUALITY_DECLARATION.md, trajectory_msgs/QUALITY_DECLARATION.md, visualization_msgs/QUALITY_DECLARATION.md
Updating obsolete links in the QUALITY_DECLARATION.md files, re: ros2/docs.ros2.org#52
=> Updating Quality Declaration

diagnostic_msgs/README.md, geometry_msgs/README.md, nav_msgs/README.md, sensor_msgs/README.md, shape_msgs/README.md, std_msgs/README.md, std_srvs/README.md, stereo_msgs/README.md, trajectory_msgs/README.md, visualization_msgs/README.md
=> Change index.ros.org -> docs.ros.org.

visualization_msgs/msg/Marker.msg
Connected to https://github.com/ros2/rviz/pull/685.
=> Document namespace scoped marker deletion.

sensor_msgs/include/sensor_msgs/fill_image.hpp, sensor_msgs/include/sensor_msgs/impl/point_cloud2_iterator.hpp, sensor_msgs/include/sensor_msgs/point_cloud2_iterator.hpp, sensor_msgs/include/sensor_msgs/point_cloud_conversion.hpp, sensor_msgs/include/sensor_msgs/point_field_conversion.hpp
Make sure the build of documentation is clean.  No functional
changes in here, though there are some formatting changes to make
things easier to document.
=> Fix rosdoc2 warnings in sensor_msgs.

sensor_msgs/CMakeLists.txt
Related: https://github.com/ros2/common_interfaces/pull/178#issuecomment-1076516076
CC: @sloretz
=> Add conditional rosidl_generator_cpp in sensor_msgs

CONTRIBUTING.md, README.md
Adapted from: https://wiki.ros.org/common_msgs
=> Copy in notes about contributing and purpose from the wiki

sensor_msgs/msg/BatteryState.msg
* Update BatteryState.msg
Signed-off-by: Ivan Zatevakhin <zatevaxin.ivan@gmail.com>
=> Replaced non-ASCII dash symbol with ASCII dash

sensor_msgs/include/sensor_msgs/image_encodings.hpp
This is similar to https://github.com/ros2/common_interfaces/pull/205, but for the other YUV formats, YUYV and UYVY.
=> Return true for isColor if format is YUYV or UYUV

nav_msgs/CMakeLists.txt, nav_msgs/action/GetMap.action
There is a TODO that mentioned the adition of this message. Happy to remove the comment and the new message if this is not required anymore
There is already a service called GetMap.srv
@SteveMacenski, @tfoote  ?
=> Removed TODO

diagnostic_msgs/QUALITY_DECLARATION.md, geometry_msgs/QUALITY_DECLARATION.md, nav_msgs/QUALITY_DECLARATION.md, sensor_msgs/QUALITY_DECLARATION.md, shape_msgs/QUALITY_DECLARATION.md, std_msgs/QUALITY_DECLARATION.md, std_srvs/QUALITY_DECLARATION.md, stereo_msgs/QUALITY_DECLARATION.md, trajectory_msgs/QUALITY_DECLARATION.md, visualization_msgs/QUALITY_DECLARATION.md
* Update branch name in links (`/master/` -> `/rolling/`)
* Update docs.ros.org links
* Apply one-sentence-per-line rule
=> Update quality declaration documents

README.md
Signed-off-by: Lukas Schäper [lukas.schaeper@wiedemann-group.com](mailto:lukas.schaeper@wiedemann-group.com)
=> Fix path to CONTRIBUTING.md

sensor_msgs_py/package.xml, sensor_msgs_py/test/test_xmllint.py
This is part of getting to https://github.com/ros2/ros2cli/issues/944 , in the sense that it fixes the core to actually do this. @sloretz FYI
=> Add ament_xmllint to sensor_msgs_py.
